import fs from 'node:fs';
import pptxgen from './.deck-build/node_modules/pptxgenjs/dist/pptxgen.es.js';
const p=new pptxgen();p.layout='LAYOUT_WIDE';p.author='Alejandro Zárate Macías';p.title='MCP · Del cuarto cerrado al mundo real';p.subject='MexAI · CIATEQ Zapopan · 30 septiembre 2026';p.lang='es-MX';
const S=p.ShapeType, C={ink:'241331',purple:'6934C6',dark:'291244',light:'F4EFFF',white:'FFFFFF',muted:'756784',lime:'D5F46A',red:'E86277',line:'C5B4DC'};
const deckNotes=[];
function t(s,v,x,y,w,h,size=28,color=C.ink,bold=false,extra={}){s.addText(v,{x,y,w,h,fontFace:'Arial',fontSize:size,color,bold,margin:0,breakLine:false,valign:'mid',isTextBox:true,...extra});}
function rect(s,x,y,w,h,fill=C.white,stroke=fill,r=0){s.addShape(r?S.roundRect:S.rect,{x,y,w,h,rectRadius:r,fill:{color:fill},line:{color:stroke,width:1.5},radius:r});}
function line(s,x,y,xx,yy,color=C.purple,width=2,arrow=false){s.addShape(S.line,{x,y,w:xx-x,h:yy-y,line:{color,width,...(arrow?{endArrowType:'triangle'}:{})}});}
function img(s,name,x,y,w,h){const file='assets/'+name;const b=fs.readFileSync(file);let iw,ih;if(name.endsWith('jpeg')){iw=726;ih=1600;}else{iw=b.readUInt32BE(16);ih=b.readUInt32BE(20);}let k=Math.min(w/iw,h/ih);s.addImage({path:file,x:x+(w-iw*k)/2,y:y+(h-ih*k)/2,w:iw*k,h:ih*k});}
function slide(label,note,dark=false){const s=p.addSlide();s.background={color:dark?C.dark:C.white};if(label)t(s,label,.6,.35,11.8,.4,14,dark?C.lime:C.purple,true);s.addNotes(note);deckNotes.push({label,note});return s;}
function act(number,title,joke,note){const s=slide('',note,true);t(s,'ACTO '+number,.85,.7,11.6,.55,22,C.lime,true);t(s,title,.85,1.7,11.6,1.3,40,C.white,true);t(s,joke,.85,3.5,11.5,2.3,51,C.white,true);}
function heading(s,v,size=38){t(s,v,.6,.95,12.1,1.05,size,C.ink,true);}
function pill(s,v,x,y,w,fill=C.light,color=C.purple,size=20){rect(s,x,y,w,.58,fill,fill,.1);t(s,v,x+.12,y+.04,w-.24,.5,size,color,true,{align:'center'});}
function node(s,v,x,y,w=2,h=.8,fill=C.light,color=C.ink,size=21){rect(s,x,y,w,h,fill,fill,.1);t(s,v,x+.12,y+.05,w-.24,h-.1,size,color,true,{align:'center'});}
function room(s,avatar){
 rect(s,4.6,1.75,7.9,4.98,C.light,C.purple);line(s,4.6,6.25,12.5,6.25,C.line,2);
 if(avatar==='6_alex_as_rag_looking_for_notes.png'){img(s,avatar,5.6,2.45,6,3.95);return;}
 rect(s,4.6,2.45,1.15,3.8,C.white,C.purple);s.addShape(S.ellipse,{x:5.47,y:4.22,w:.1,h:.1,fill:{color:C.purple},line:{color:C.purple}});
 const bubble=avatar==='4_alex_as_llm_answers_by_memory.png'||avatar==='5_alex_as_llm_alhucinating.png'||avatar==='extra_alex_palmface.png';img(s,avatar,6.55,bubble?3.23:2.45,4.75,bubble?3.05:3.95);
}
function network(s,x,y,w,h,n,m,clean=false){let left=1.05,right=1.2;const ly=i=>y+.3+i*(h-.6)/(n-1||1), ry=j=>y+.3+j*(h-.6)/(m-1||1);
 for(let i=0;i<n;i++)for(let j=0;j<m;j++)line(s,x+left,ly(i)+.27,x+w-right,ry(j)+.27,clean?C.purple:(i+j)%2?C.red:C.line,clean?1.1:1.5);
 for(let i=0;i<n;i++)node(s,['Chat','IDE','Agente'][i],x,ly(i),left,.55,C.ink,C.white,14);
 for(let j=0;j<m;j++)node(s,['Drive','GitHub','CRM','Interno'][j],x+w-right,ry(j),right,.55,clean?C.purple:C.light,clean?C.white:C.ink,14);
}
// 01 Opening and presenter, in a single composition.
{let s=slide('',`Abrir con la pregunta: ¿quién sabe qué es MCP? Pedir manos, aceptar “me suena” y “creo que ya lo uso”. Pausa. Soy Alejandro Zárate Macías, AI Engineer del Instituto de Información Estadística y Geográfica. Trabajo con recuperación de herramientas en español y visión por computadora. Hoy vamos a sacar a alguien muy inteligente de una habitación y descubrir por qué conectar cosas termina siendo un trabajo de tiempo completo.`,true);
 t(s,'MCP',.65,.75,7.3,1.8,116,C.lime,true);t(s,'Del cuarto cerrado\nal mundo real',.72,2.65,8.0,1.55,43,C.white,true);img(s,'1_alex_and_mexai.png',8.55,.8,4.1,4.6);t(s,'¿Quién sabe qué es MCP?',.74,4.66,8.2,.65,30,C.white,true);
 img(s,'alex_real.jpeg',.72,5.65,.6,1.25);t(s,'Alejandro Zárate Macías',1.5,5.66,10,.42,22,C.white,true);t(s,'AI Engineer · Instituto de Información Estadística y Geográfica',1.5,6.13,10.8,.42,17,C.white);t(s,'MexAI   /   CIATEQ Zapopan   /   30 septiembre 2026',1.5,6.64,10.8,.35,15,C.lime);}
// 02–05 same room, changing capabilities.
act('I','Un cerebro encerrado','Leyó todo internet.\nLe faltó salir del cuarto.','Pausa antes de comenzar la historia. Leer el remate y señalar que nuestro personaje tiene conocimientos, pero no acceso automático al mundo exterior.');
{let s=slide('ACTO I   /   UN CEREBRO ENCERRADO',`Vamos a hacer un experimento bastante cuestionable: encerramos a alguien en un cuarto y le damos todo lo que pueda leer. Libros, artículos, conversaciones, tutoriales, respuestas de foros… Que aprenda todo lo que pueda. Nuestro personaje estudia, relaciona cosas y memoriza. Pausa: ya sabe muchísimo, pero sigue encerrado. Esta es la analogía humana del entrenamiento; técnicamente un LLM aprende patrones en sus parámetros y genera respuestas condicionadas al contexto, no consulta una memoria literal de todo internet. Transición: ahora le hacemos preguntas por la puerta.`);t(s,'Lo encerramos.\nQue aprenda\ntodo lo que pueda.',.65,2.1,3.8,2.4,35,C.ink,true);t(s,'Libros, foros, tutoriales…',.65,5.15,3.65,.85,23,C.purple);room(s,'3_alex_as_llm_learning.png');}
{let s=slide('TOC, TOC… UNA PREGUNTA',`Ahora alguien toca la puerta y pregunta algo que nuestro personaje estudió. Él piensa: “Eso lo leí… a ver, me acuerdo”. Recupera lo que cree recordar, relaciona ideas y responde. Y muchas veces la respuesta sirve: por eso estos modelos son tan útiles. Dejar que el público reconozca la situación de contestar un examen sin apuntes. La memoria es una analogía divulgativa, no el mecanismo literal del modelo: éste genera texto a partir de patrones aprendidos y del contexto, y puede razonar además de reproducir información. Transición con una pausa: el problema es cuando se le cruzan los cables y la seguridad se queda intacta.`);room(s,'4_alex_as_llm_answers_by_memory.png');t(s,'Le preguntas.\nSe acuerda.\nTe responde.',.65,2.35,3.75,2.2,38,C.ink,true);node(s,'“Eso lo leí…\nsí me acuerdo.”',6.45,1.95,5.55,1.1,C.white,C.purple,27);pill(s,'Hasta aquí, todo bien.',.65,5.35,3.75,C.lime,C.ink,20);}
{let s=slide('PERO A VECES… SALE EL ALUCÍN',`Puede mezclar términos, atribuir una idea a quien no era o inventarse una explicación; y decirlo con una seguridad espectacular. Aquí entra el alucín: en la analogía, se cree muy cabrón, pero anda inventando. No es que el modelo tenga ego o quiera mentir; llamamos alucinación a una respuesta falsa o sin fundamento presentada como plausible. Preguntar: “¿Cuánto vendimos ayer?”. Imitar una voz muy solemne: “Basándome en patrones históricos… ochenta y cinco mil, sin duda”. Pausa. “Mi hermano, ni acceso al sistema tienes”. La cifra es deliberadamente ficticia y sin fuente. Remate: “Se le olvidó el dato, pero no la confianza”. No todos los errores son por información ausente: también puede fallar con contexto disponible. Transición: no queremos una predicción ni un cuento convincente; queremos el dato. Vamos a pasarle el reporte por debajo de la puerta.`);room(s,'5_alex_as_llm_alhucinating.png');t(s,'¿Cuánto\nvendimos\nayer?',.65,2.15,3.75,2.3,43,C.ink,true);node(s,'“$85,000.\nSin duda, mi estimado.”',6.05,1.95,5.95,1.1,C.white,C.purple,25);pill(s,'Fuente: créeme, bro.',.65,5.35,3.8,C.lime,C.ink,21);}
{let s=slide('RAG   /   CONTEXTO POR DEBAJO DE LA PUERTA',`Después del alucín, abrir con: “A ver, aquí está el reporte. Léelo antes de contestar”. El reporte dice 42 mil, no los 85 mil inventados de la escena anterior. Ahora la respuesta tiene una fuente que podemos contrastar. RAG recupera fragmentos relevantes de fuentes y los incorpora al contexto del modelo. Puede ayudar con información reciente o privada si el índice y los permisos están bien mantenidos. No es reentrenar el modelo. En la escena, los papeles son el contexto recuperado. El personaje ahora responde usando el reporte de ayer. Ejemplo ficticio: 42 mil pesos. No prometer que RAG elimina errores. Transición: ya tiene el reporte; ahora pidámosle que haga algo.`);room(s,'6_alex_as_rag_looking_for_notes.png');t(s,'Aquí está\nel reporte.',.65,2.05,3.6,1.7,41,C.ink,true);node(s,'REPORTE DE AYER\n$42,000',.7,4.2,3.35,1.3,C.lime,C.ink,24);line(s,4.05,5,5.4,5.8,C.purple,3,true);t(s,'Pregunta  →  recuperar  →  contexto  →  respuesta',.65,6.92,12,.35,20,C.purple,true,{align:'center'});}
{let s=slide('SABER EXPLICAR ≠ EJECUTAR',`Pedir “Ahora genera la factura”. El personaje explica impecablemente los pasos, pero en esta configuración sólo responde texto. RAG por sí solo no ejecuta la operación. Puede coexistir con tools y agentes, así que esto es una elección de arquitectura del ejemplo, no una prohibición universal. Remate: excelente tutorial, cero facturas. Transición al acto II: vamos a darle un cuerpo y herramientas.`);room(s,'extra_alex_palmface.png');t(s,'“Ahora genera\nla factura.”',.65,2.1,3.75,1.5,37,C.ink,true);node(s,'1. Abre el sistema…\n2. Captura los datos…',6.05,1.95,5.9,1.1,C.white,C.purple,25);pill(s,'Facturas generadas: 0',.65,5.2,3.8,C.lime,C.ink,20);}
// 06–07 agent.
act('II','Le damos un cuerpo','Ya da consejos.\nAhora que haga algo.','Retomar la factura que nunca se generó. Vamos a darle herramientas y un sistema que coordine su ejecución.');
{let s=slide('ACTO II   /   LE DAMOS UN CUERPO',`El LLM aporta el razonamiento y propone pasos o llamadas. El sistema agente coordina el ciclo, ejecuta herramientas con validación y permisos, observa resultados y decide si continuar. Las tools son funciones o capacidades concretas, no necesariamente objetos físicos. Tool calling y agentes existían antes de MCP. No todos los agentes requieren autonomía ilimitada. Transición: veamos una vuelta del ciclo sin magia.`);heading(s,'Del “te explico” al “lo hago”.');img(s,'7_alex_as_agent_with_tools.png',4.55,2,4.25,4.65);t(s,'LLM',.8,2.65,3.25,.6,35,C.purple,true);t(s,'el cerebro',.8,3.3,3.25,.55,24);line(s,3.55,3.25,4.6,3.25);t(s,'TOOLS',9.2,2.65,3.3,.6,35,C.purple,true);t(s,'las capacidades',9.2,3.3,3.5,.55,24);line(s,8.7,3.25,9.05,3.25);pill(s,'AGENTE = decide + ejecuta + observa',2.35,6.4,8.6,C.ink,C.white,25);}
{let s=slide('UNA VUELTA DEL CICLO',`Ejemplo ficticio de tool calling anterior e independiente de MCP. El usuario pregunta por las ventas. El modelo propone consultar_ventas con una fecha; el runtime valida y ejecuta, no el texto del modelo por sí mismo. La función devuelve un resultado estructurado, que vuelve al contexto del modelo. Este redacta una respuesta. Puede haber varios ciclos, fallos, reintentos o confirmación humana. La fecha se resuelve desde “ayer” usando el calendario y la zona horaria del usuario.`);heading(s,'Una llamada. Un resultado. Una respuesta.');
 const xs=[.65,3.85,7.05,10.05];const ws=[2.7,2.7,2.5,2.65];['Usuario','LLM propone','Runtime ejecuta','LLM responde'].forEach((v,i)=>{t(s,v,xs[i],2.35,ws[i],.5,21,C.purple,true);if(i<3)line(s,xs[i]+ws[i],4,xs[i+1]-.1,4,C.purple,2,true);});
 node(s,'¿Cuánto\nvendimos ayer?',.65,3.25,2.7,1.65,C.light,C.ink,26);node(s,'consultar_ventas\nfecha="2026-09-29"',3.85,3.25,2.7,1.65,C.dark,C.white,16);node(s,'{"total": 42000,\n "moneda": "MXN"}',7.05,3.25,2.5,1.65,C.light,C.ink,17);node(s,'Ayer vendimos\n$42,000 MXN.',10.05,3.25,2.65,1.65,C.lime,C.ink,24);t(s,'Tool calling ya existía antes de MCP.',.65,6,12,.6,28,C.purple,true,{align:'center'});}
// 08 pause / 09 punchline.
act('III','El infierno de las integraciones','“Solo hay que\nconectarlo a la API”.','Mostrar la frase y dejar tres segundos de silencio. Preguntar con la mirada quién ha escuchado eso. Avanzar para revelar OAuth, permisos, tokens y el coste escondido.');
{let s=slide('ACTO III   /   EL INFIERNO DE LAS INTEGRACIONES',`Revelación. Enumerar apenas dos o tres problemas, sin leer todas las palabras: OAuth, scopes, refresh tokens, diferencias de SDK y versiones. La API no es el problema; el trabajo repetido y las diferencias entre sistemas sí. Remate: “Normalmente pronunciado por alguien que no va a conectarlo”. Pausa para la risa. MCP no borrará la autenticación ni arreglará una API defectuosa.`,true);t(s,'“Solo”.',.65,1.02,5.5,1.2,72,C.lime,true);img(s,'8_alex_as_dev_making_connectors_by_hand.png',4.1,1.55,5.4,4.75);
 [['OAuth',.8,2.75,30],['refresh tokens',.8,4.1,24],['scopes',10,2.35,29],['SDK v2 / API v3',9.25,4.7,22],['documentación',.7,5.65,25],['permisos',9.8,3.65,27]].forEach(([v,x,y,z])=>t(s,v,x,y,3.2,.65,z,C.white,true));t(s,'Normalmente pronunciado por alguien que no va a conectarlo.',.7,6.65,11.9,.45,21,C.lime,false,{align:'center'});}
{let s=slide('EL PROBLEMA CRECE CON CADA CLIENTE',`Recorrer los paneles de izquierda a derecha. Un cliente y un sistema: una conexión. Tres clientes con dos sistemas: seis combinaciones posibles. Tres por cuatro: doce. Son combinaciones potenciales, no una obligación de implementar doce SDK completos; pueden existir adaptadores compartidos. El propósito del diagrama es mostrar la multiplicación de contratos particulares. Transición: el agente funciona; lo que no escala bien es rehacer el cableado.`);heading(s,'Primero un cable. Después, esto.');
 [[.65,1,1,'1 × 1'],[4.95,3,2,'3 × 2'],[9.25,3,4,'3 × 4']].forEach(([x,n,m,v])=>{t(s,v,x,2.15,3.55,.6,30,C.purple,true,{align:'center'});network(s,x,3.1,3.45,2.65,n,m);});t(s,'clientes × sistemas = combinaciones posibles',.65,6.5,12,.5,25,C.muted,false,{align:'center'});}
// 11–14 MCP resolution and technical core.
act('IV','MCP: un enchufe común','El conector número 37\nya no me dio felicidad.','Después del caos, pausa. Introducir la necesidad de compartir un contrato de integración. MCP reduce trabajo repetido, sin eliminar adaptadores ni permisos.');
{let s=slide('ACTO IV   /   DEJEMOS DE REINVENTAR LA RUEDA',`Revelar MCP como resolución del problema, no como un nuevo cerebro. Model Context Protocol estandariza cómo las aplicaciones compatibles descubren y consumen capacidades externas. Analogía del enchufe común: el conector facilita compatibilidad, pero cada aparato sigue haciendo su trabajo. Una función expuesta en HTTP sigue siendo sólo una API si no implementa el contrato MCP. Los servidores adaptan sistemas existentes; no desaparece todo el trabajo de integración.`,true);t(s,'MCP',.7,1.25,6,1.6,106,C.lime,true);t(s,'Un enchufe común.',.75,3.18,7.6,.8,40,C.white,true);t(s,'Descubrir capacidades.\nInvocarlas con un contrato compartido.',.78,4.3,7.1,1.3,27,C.white);img(s,'9_alex_discovering_mcp.png',8.6,1.25,4,4.7);t(s,'Model Context Protocol',.78,6.35,9,.55,23,C.lime);}
{let s=slide('LA MISMA TAREA   /   A MANO',`Primera mitad de la comparación visual. Dejar que el público vea al personaje atrapado entre cables. Decir: “Cada sistema tiene su manera. Y aquí estoy yo, haciendo que todas se entiendan”. Pausa. El presentador marca el ritmo y avanza a la siguiente diapositiva para revelar el cambio; no se requiere animación automática. La imagen es una metáfora del trabajo de integración, no un diagrama del protocolo.`);t(s,'A mano.',.65,.85,12,.75,39,C.ink,true);img(s,'8_alex_as_dev_making_connectors_by_hand.png',.75,1.8,11.8,5.1);}
{let s=slide('LA MISMA TAREA   /   CON MCP',`Segunda mitad de la comparación visual. Mantener la pausa y señalar el diagrama del asset 10: aplicaciones de IA a un lado, capacidades externas al otro, una interfaz común entre ambas. Decir: “Los sistemas siguen siendo distintos. Lo que compartimos es la forma de descubrir y pedir sus capacidades”. La ilustración resume la idea; no representa un servidor central obligatorio ni implica que el modelo sea el cliente MCP. El cliente es un componente del host, como se precisa en la siguiente diapositiva. Los servidores MCP adaptan sus sistemas y conservan sus permisos y reglas. Exponer una función no equivale por sí solo a implementar MCP. El presentador controla la transición entre ambas imágenes.`);t(s,'Con MCP.',.65,.85,12,.75,39,C.purple,true);img(s,'10_alex_explaining_mcp_diagram.png',.65,1.8,12,5.1);}
{let s=slide('POR DENTRO   /   HOST ≠ CLIENTE',`Host: la aplicación que coordina modelo, interfaz, permisos y conexiones. Cliente MCP: componente de protocolo dentro del host, conectado a un servidor. El host puede tener varios clientes. Servidor: ofrece capacidades y adapta el sistema externo. MCP usa mensajes JSON-RPC; los transportes habituales son stdio para procesos locales y Streamable HTTP para acceso remoto. El modelo no habla necesariamente MCP: el host hace esa mediación. Fuente: https://modelcontextprotocol.io/specification/2025-11-25/architecture`);heading(s,'El cliente vive dentro del host.');rect(s,.65,2.35,5.7,3.95,C.light,C.purple);t(s,'HOST  ·  Chat / IDE / aplicación',.9,2.6,5.2,.55,25,C.purple,true);node(s,'Modelo + interfaz + control',1,3.6,4.95,.75,C.white,C.ink,24);node(s,'Cliente MCP A',3.7,4.55,2.25,.65,C.purple,C.white,18);node(s,'Cliente MCP B',3.7,5.45,2.25,.65,C.purple,C.white,18);
 node(s,'Servidor A',7.5,4.5,2.05,.75,C.dark,C.white,22);node(s,'Servidor B',7.5,5.4,2.05,.75,C.dark,C.white,22);node(s,'API / datos',10.55,4.5,2.1,.75,C.light,C.ink,21);node(s,'Otro sistema',10.55,5.4,2.1,.75,C.light,C.ink,20);line(s,5.95,4.88,7.5,4.88,C.purple,2,true);line(s,5.95,5.78,7.5,5.78,C.purple,2,true);line(s,9.55,4.88,10.55,4.88,C.purple,2,true);line(s,9.55,5.78,10.55,5.78,C.purple,2,true);t(s,'JSON-RPC   /   stdio local   /   Streamable HTTP remoto',.65,6.72,12,.4,21,C.muted,false,{align:'center'});}

{let s=slide('EL SERVIDOR OFRECE UN CATÁLOGO',`Tools: funciones invocables, por ejemplo crear_ticket. Resources: contenido identificable por URI que el cliente puede leer. Prompts: plantillas reutilizables que el usuario o cliente puede seleccionar. El soporte de cada primitiva depende del cliente. Un flujo típico negocia capacidades y versión, lista herramientas, y hace tools/call con nombre y argumentos. La herramienta se describe con nombre, descripción y JSON Schema; el resultado puede ser contenido o datos estructurados. resources/list y resources/read, prompts/list y prompts/get son operaciones diferentes. La selección de una tool la decide el sistema agente; MCP transporta la solicitud, no razona por él. Fuente: https://modelcontextprotocol.io/specification/2025-11-25/server/index`);heading(s,'Qué puedes hacer, leer y preparar.');[['TOOLS','crear_ticket(título)','Ejecutar'],['RESOURCES','expediente://123','Leer contexto'],['PROMPTS','resumir_expediente','Usar una plantilla']].forEach(([a,b,c],i)=>{let x=.65+i*4.25;t(s,a,x,2.3,3.8,.65,30,C.purple,true);t(s,b,x,3.25,3.8,.7,20,C.ink,true,{fontFace:'Courier New'});t(s,c,x,4.18,3.8,.55,23,C.muted);});rect(s,.65,5.45,12,1.23,C.dark);t(s,'Capacidades   →   tools/list   →   tools/call   →   resultado',.93,5.7,11.45,.68,22,C.white,true,{fontFace:'Courier New',align:'center'});}
// 15–17 office and code.
act('V','Volvamos a la oficina','El sistema es de 2017.\nLa contraseña también.','Remate sobre sistemas heredados. Pasar al ejemplo de Mesa de ayuda: ya funciona, ya tiene una API y podemos reutilizarlo.');
{let s=slide('ACTO V   /   VOLVAMOS A LA OFICINA',`Sistema ficticio de Mesa de ayuda, funcionando desde 2017. Ya gestiona tickets, expedientes y reportes mediante una API. No necesita reinventarse para ofrecer capacidades a una aplicación de IA. Un servidor MCP puede exponer sólo operaciones seleccionadas, delegando reglas del negocio y permisos al sistema real. No recomendar exponer indiscriminadamente cada endpoint. El ejemplo empresarial es conceptual y no asegura que la demo local tenga todas esas operaciones.`);t(s,'Funciona desde 2017.',.65,1.1,12,.9,43,C.ink,true);rect(s,.75,2.6,7.1,3.45,C.light,C.purple);t(s,'MESA DE AYUDA',1.05,2.9,6.5,.5,25,C.purple,true);t(s,'Tickets\nExpedientes\nReportes',1.1,3.75,3.5,1.8,30,C.ink,true);node(s,'API\nexistente',5.2,3.75,2.1,1.5,C.purple,C.white,28);line(s,7.85,4.25,8.7,4.25,C.purple,3,true);node(s,'Servidor\nMCP',8.7,3.35,3.7,1.8,C.lime,C.ink,32);t(s,'Las operaciones ya saben hacer el trabajo.',.75,6.45,11.8,.55,28,C.purple,true);}
{let s=slide('LA TENTACIÓN',`Segundo gran chiste. Decir con entusiasmo falso: “¡Otro chatbot corporativo, marca registrada!”. Enumerar: otra aplicación, otra contraseña, otra interfaz, otra capacitación. Pausa. La alternativa es reutilizar el sistema y ofrecer capacidades a clientes compatibles ya adoptados. A veces sí se necesita una interfaz especializada; MCP no la prohíbe ni garantiza que cualquier cliente cubra todos los flujos.`);t(s,'¡Otro chatbot\ncorporativo™!',.65,1.05,7.2,1.9,50,C.purple,true);img(s,'11_alex_as_person_tired_of_new_chatbot_for_just_one_system.png',7.4,1.5,5.2,4.8);t(s,'Otra app.\nOtra contraseña.\nOtro “¿dónde era?”.',.7,3.8,6.1,2.0,33,C.ink);t(s,'Podemos reutilizar lo que ya funciona.',.7,6.6,11.8,.5,27,C.purple,true);}
{let s=slide('FASTMCP   /   EL PROTOCOLO YA TIENE IMPLEMENTACIÓN',`Ejemplo pequeño y sintácticamente válido, no servicio listo para producción. Requiere fastmcp y httpx y una API ficticia local en el puerto 8000 con GET /tickets. FastMCP deriva el esquema de tipos y la descripción del docstring, registra la tool y atiende el transporte HTTP. No es necesario escribir a mano todos los mensajes JSON-RPC. Faltan, de manera deliberada, propagación de identidad y autorización: deben conectarse a las reglas reales. No confundir tipado con autorización. No ejecutar este ejemplo esperando que el endpoint exista en la app actual. Fuente: https://gofastmcp.com/servers/tools y https://gofastmcp.com/deployment/http`,true);t(s,'Tu función. El contrato MCP.',.65,.98,12,.85,39,C.white,true);
 const code='from fastmcp import FastMCP\nimport httpx\n\nmcp = FastMCP("Mesa de ayuda")\n\n@mcp.tool\ndef listar_tickets() -> list[dict]:\n    """Consulta los tickets de la API."""\n    r = httpx.get("http://127.0.0.1:8000/tickets")\n    r.raise_for_status()\n    return r.json()\n\nmcp.run(transport="http", port=8001)';
 t(s,code,.85,2.08,11.65,4.73,23,C.white,false,{fontFace:'Courier New',valign:'top'});fs.writeFileSync('output/redesign-review/ejemplo_fastmcp.py',code+'\n');}
// 18 clients.
act('VI','De la terminal al chat','El usuario pidió ayuda.\nLe mandamos un JSON.','Pausa. Introducir cómo clientes que la gente ya usa acercan estas capacidades sin exigir un chatbot por cada sistema.');
{let s=slide('ACTO VI   /   DE LA TERMINAL AL CHAT HABITUAL',`Herramientas de desarrollo como Claude Code, Codex y OpenCode permiten configurar servidores MCP. Sus transportes, permisos, autenticación y soporte de primitivas varían. ChatGPT ofrece apps MCP con modo desarrollador según plan, plataforma y políticas del espacio; verificar acceso antes de la charla. Claude ofrece conectores remotos y opciones locales según producto. No dar por hecho que todos usan el mismo archivo de configuración ni que todos exponen tools, resources y prompts igual. Lo común es poder reutilizar capacidades sin crear un chatbot para cada sistema. Fuentes: https://code.claude.com/docs/en/mcp ; https://developers.openai.com/codex/mcp ; https://opencode.ai/docs/mcp-servers/ ; https://help.openai.com/en/articles/12584461-developer-mode-and-mcp-apps-in-chatgpt ; https://support.claude.com/en/articles/11175166-get-started-with-custom-connectors-using-remote-mcp`);heading(s,'La herramienta cambia. El sistema se reutiliza.');t(s,'En desarrollo',.7,2.45,5.5,.6,28,C.purple,true);t(s,'Claude Code\nCodex\nOpenCode',.7,3.35,5.5,2.15,38,C.ink,true);t(s,'En el chat',7,2.45,5.5,.6,28,C.purple,true);t(s,'ChatGPT\nClaude',7,3.35,5.5,1.4,38,C.ink,true);t(s,'Apps / conectores según producto,\nplan y permisos del espacio.',7,5,5.4,1.0,22,C.muted);line(s,6.4,2.4,6.4,6.1,C.line,1);}
// 19–22 demo with honest fallback status.
act('VII','Demo','En mi laptop funciona.\nAhorita vemos aquí.','Pausa y sonrisa. Presentar la demo y recordar que existe un recorrido de respaldo mediante capturas o video.');
{let s=slide('ACTO VII   /   DEMO',`Introducir el montaje de la demo: FastAPI sirve la API y aplicación, FastMCP expone capacidades, Funnel ofrece una URL HTTPS pública, ChatGPT conecta cuando el plan y el espacio lo permiten. La solicitud viaja de derecha a izquierda y el resultado vuelve. Tailscale Funnel aporta conectividad, NO sustituye autenticación ni autorización. En el repositorio actual hay una demo de consultas y datos sintéticos; no hay evidencia de una tool de escritura. El recorrido de video pedido por Alejandro usa apps del catálogo, la plataforma como web/API REST, conexión a ChatGPT y consultas contrastadas en la web. Las escrituras quedan como ejemplo conceptual anterior. Chiste opcional: “Como todo sistema profesional de producción, está corriendo desde mi laptop”. Fuente: https://tailscale.com/docs/features/tailscale-funnel La ilustración 12 muestra a Alejandro preparando la demo. Sus rutas son ilustrativas; las operaciones reales se muestran en el video. Los personajes representan aplicaciones compatibles, cuyo soporte concreto varía.`,false);t(s,'De mi laptop a tu chat.',.65,.85,12,.8,40,C.purple,true);img(s,'12_alex_presenting_fastmcp.png',.75,1.9,11.8,4.65);t(s,'FastAPI  →  FastMCP  →  Tailscale Funnel  →  ChatGPT',.7,6.7,12,.45,23,C.purple,true,{align:'center'});}

function media(s,number,title,x,y,w,h){t(s,number+'  '+title,x,y,w,.55,23,C.purple,true);rect(s,x,y+.8,w,h,C.light,C.line);t(s,'Insertar captura o fragmento del video',x+.25,y+.8+h/2-.35,w-.5,.7,19,C.muted,false,{align:'center'});}
{let s=slide('DEMO   /   PRIMERO LO CONOCIDO',`Recorrido confirmado por Alejandro. Primer fragmento: usar una app disponible en el catálogo de ChatGPT y mostrar qué capacidad aporta; no afirmar que todas las apps del catálogo son servidores MCP intercambiables ni que tienen idénticos permisos. Segundo fragmento: abrir nuestra plataforma como web y como API REST, ejecutar una consulta y mostrar los mismos datos. La plataforma ya sirve antes de conectar un chat. Espacios editables para capturas del video, solicitados por el presentador; no son evidencia de ejecución. Elegir una consulta real del catálogo y ocultar cualquier credencial en la grabación.`);heading(s,'Primero, lo que ya funciona.');media(s,'01','Apps del catálogo de ChatGPT',.65,2.2,5.75,3.25);media(s,'02','Nuestra plataforma: web / REST',6.95,2.2,5.75,3.25);t(s,'Una capacidad disponible. Una API que ya funciona.',.65,6.65,12,.45,24,C.purple);}
{let s=slide('DEMO   /   CONECTAR Y CONTRASTAR',`Tercer fragmento: conectar la plataforma a ChatGPT mediante la URL MCP remota y las opciones habilitadas para la cuenta. Mostrar que se descubren las herramientas; ocultar credenciales y no hacer depender la explicación de nombres de botones que puedan cambiar. Cuarto fragmento: hacer una consulta desde ChatGPT y volver a la web, ejecutando la misma consulta y verificando filtros, periodo y resultados. Recorrido de consultas solicitado por Alejandro, sin afirmar una escritura que la aplicación no ofrece. Espacios editables para capturas del video.`);heading(s,'El mismo sistema, desde el chat.');media(s,'03','Conectar la plataforma a ChatGPT',.65,2.2,5.75,3.25);media(s,'04','Consultar y verificar en la web',6.95,2.2,5.75,3.25);t(s,'Mismos filtros. Mismo periodo. Mismos resultados.',.65,6.65,12,.45,24,C.purple);}
{let s=slide('PLAN B   /   SI EL WIFI DECIDE PARTICIPAR',`Insertar aquí el video local de los cuatro pasos, o usar las cuatro capturas de las diapositivas anteriores. Orden: apps del catálogo de ChatGPT, plataforma web y API REST, conexión MCP a ChatGPT, consulta y verificación en la web. Probar la reproducción local sin internet antes del evento. Alejandro indicó que aún no existen las capturas ni el video y solicitó dejar los espacios. No afirmar que este archivo contiene una grabación. Si no se incorpora a tiempo, usar el diagrama y narrar la secuencia, marcándola como explicación y no ejecución en vivo.`);heading(s,'El video no necesita el wifi del auditorio.');rect(s,.85,2.3,11.6,3.85,C.dark);t(s,'ESPACIO PARA VIDEO LOCAL',1.2,3.5,10.9,.7,30,C.white,true,{align:'center'});t(s,'Catálogo  →  Web / REST  →  Conexión  →  Consultas',1.2,4.65,10.9,.55,22,C.lime,false,{align:'center'});t(s,'Alternativa: las cuatro capturas de las diapositivas anteriores.',.85,6.65,11.6,.45,22,C.purple);}
// 23 security.
act('VIII','Seguridad y cierre','Al alucín le dimos tools.\n¿Qué podría salir mal?','Recuperar el personaje del primer acto. Conectar el chiste con identidad, permisos, confirmación y auditoría.');
{let s=slide('ACTO VIII   /   MÁS CAPACIDAD, MÁS RESPONSABILIDAD',`Leer el remate y hacer una pausa. “Si tu agente toma malas decisiones, MCP ahora puede permitirle tomar malas decisiones en más sistemas”. Después aterrizar cuatro controles: autenticación verifica identidad; autorización verifica la operación y el recurso permitidos; confirmación explícita antes de efectos importantes; auditoría registra quién pidió qué, qué tool se ejecutó y el resultado. Aplicar mínimo privilegio y validación en el servidor, no confiar sólo en el prompt. Contenido externo puede contener prompt injection; tratarlo como datos no confiables. HTTPS/Funnel no reemplazan estos controles. Los errores y duplicados también requieren gestión, especialmente al reintentar escrituras.`);t(s,'Malas decisiones.\nAhora en más sistemas.',.65,1.1,8.5,1.6,43,C.ink,true);img(s,'13_alex_with_shield_of_auth.png',9.3,1.05,3.4,3.2);[['Autenticación','¿Quién eres?'],['Autorización','¿Qué puedes hacer?'],['Confirmación','¿Lo ejecutamos?'],['Auditoría','¿Qué ocurrió?']].forEach(([a,b],i)=>{let x=.65+i*3.2;t(s,a,x,4.8,3.0,.55,23,C.purple,true);t(s,b,x,5.6,3.0,.7,22,C.ink);});}
// Contact placeholders and short closing.
{let s=slide('SIGAMOS LA CONVERSACIÓN',`Espacios solicitados por Alejandro para incorporar QR reales. Reemplazar los cuadros con los códigos de sus redes y del repositorio, y editar las etiquetas. No se generaron códigos ficticios ni se inventaron enlaces. Probar cada QR desde el tamaño de proyección antes de presentar. Dejar unos segundos para escanear y pasar al cierre.`);heading(s,'Nos vemos en las redes. Y en el repo.');[['Mis redes','@tu_usuario'],['Más redes','@tu_usuario'],['Repositorio','URL del repo']].forEach(([label,url],i)=>{let x=1.25+i*4;t(s,label,x,2.2,2.8,.6,26,C.purple,true,{align:'center'});rect(s,x,3.05,2.8,2.8,C.light,C.line);t(s,'TU QR',x+.2,4.1,2.4,.6,28,C.muted,true,{align:'center'});t(s,url,x-.25,6.2,3.3,.45,19,C.muted,false,{align:'center'});});}
{let s=slide('',`Recuperar oralmente la progresión: LLM responde, RAG aporta contexto, agentes coordinan acciones y MCP estandariza conexiones. Son capacidades combinables, no etapas excluyentes ni una cronología universal. Cierre oral: “MCP no apareció porque antes fuera imposible conectar agentes con herramientas; apareció porque estábamos cansados de construir el mismo puente una y otra vez”. Pausa. Volver a pedir manos: “¿Y ahora quién sabe qué es MCP?”. Dejar la ilustración en pantalla durante preguntas.`,true);t(s,'¿Y ahora quién\nsabe qué es MCP?',.8,2.25,7.15,2.2,48,C.white,true);img(s,'extra_alex_with_pc.png',8.15,1.45,4.6,4.9);}
if(p._slides.length!==34)throw Error('Expected 34 slides');
await p.writeFile({fileName:'output/MCP-MexAI-redisenada.pptx'});
fs.writeFileSync('output/MCP-MexAI-notas.md', '# Notas del presentador\n\n'+deckNotes.map((n,i)=>`## ${String(i+1).padStart(2,'0')} · ${n.label|| (i===0?'Apertura':'Cierre')}\n\n${n.note}\n`).join('\n'));
console.log('34 diapositivas + notas exportadas');
